### ISSUE TITLE
Deploy removes custom domain name

### ISSUE THREAD

**Issue by serhiicss** [shinnn/gulp-gh-pages#111] opened 2017-05-17 21:31 UTC
Once I run gulp-gh-pages, it deploys to master, but removes custom domain name from repository, thus making website unavailable. It changes the domain name to username.guthub.io in settings.

I am using github pages with custom domain name. 

How to prevent it from removing the domain name?

[https://i.imgur.com/7EXJ1OO.png](https://i.imgur.com/7EXJ1OO.png)

**Comment by shinnn** [comment] 2017-05-18 06:01
Duplicate of https://github.com/shinnn/gulp-gh-pages/issues/105

Answer: https://github.com/shinnn/gulp-gh-pages/issues/105#issuecomment-262732454

> Update your gulpfile's glob pattern to include `CNAME` file and this problem will be fixed.

**Closed by shinnn** 2017-05-18 06:01 UTC
