### ISSUE TITLE
Error in plugin 'gulp-gh-pages'

### ISSUE THREAD

**Issue by jdnichollsc** [shinnn/gulp-gh-pages#104] opened 2016-10-06 17:25 UTC
Hi man,

Check the issue http://screencast.com/t/LWnkWP7Hgt

Message:
    Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git rev-list --pretty=raw
 --skip=0 --max-count=10 gh-pages"
fatal: ambiguous argument 'gh-pages': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Details:
    killed: false
    code: 128
    signal: null
    cmd: C:\WINDOWS\system32\cmd.exe /s /c "git rev-list --pretty=raw --skip=0 -
-max-count=10 gh-pages"

Regards, Nicholls

**Comment by interglobalmedia** [comment] 2016-10-18 18:21
I have the same issue but on OSX 10.11.6. This is what I received in Terminal:

`[14:06:57] Using gulpfile ~/Development/pomodoro-animated-timer/gulpfile.js
[14:06:57] Starting 'deploy'...
[14:06:57] [gh-pages] Cloning repo
[14:06:57] [gh-pages] Checkout branch `gh-pages`
[14:06:57] [gh-pages] Updating repository
[14:06:58] 'deploy' errored after 1.07 s
[14:06:58] Error in plugin 'gulp-gh-pages'
Message:
    Command failed: git pull  
From github.com:interglobalmedia/pomodoro-animated-timer
   8854751..b410845  master     -> origin/master
Your configuration specifies to merge with the ref 'refs/heads/gh-pages'
from the remote, but no such ref was fetched.

Details:
    killed: false
    code: 1
    signal: null
    cmd: git pull  
`
My current version of Node is 6.8.1 and npm 3.10.8.

**Comment by jdnichollsc** [comment] 2016-10-24 05:22
Any updates to fix this very useful gulp plugin? :(

**Comment by shinnn** [comment] 2016-10-24 12:17
Duplicate of https://github.com/shinnn/gulp-gh-pages/issues/54

**Closed by shinnn** 2016-10-24 12:17 UTC
