### ISSUE TITLE
Not resolving promise after 'Copying files to repository'

### ISSUE THREAD

**Issue by sintell** [shinnn/gulp-gh-pages#75] opened 2015-10-19 16:46 UTC
Hi, I'm using `node@4.2.1`, with `gulp-gh-pages@0.5.3` and it doesn't work in my gulp task:
```js
gulp.task('gh-pages', ['build'], function() {
    var directory = 'gh-pages-temp';

    return gulp.src(config.build.docs.root + '/**/*')
        .pipe(ghPages({
                remoteUrl: config.ghPages.gitUrl,
                cacheDir: directory,
                branch: 'gh-pages'
            }).on('end', function() {
                console.log('end'); // this is never got called
            })
        );
});
```

```
[18:22:34] [gh-pages (gh-pages-test)] Cloning repo
[18:22:34] [gh-pages (gh-pages-test)] Checkout remote branch `gh-pages-test`
[18:22:34] [gh-pages (gh-pages-test)] Updating repository
[18:22:36] [gh-pages (gh-pages-test)] Copying files to repository
```
And here the task is stuck and never finishes. As far as I dig into sources -- [here](https://github.com/shinnn/gulp-gh-pages/blob/a538d858db1acf0591bd0ecccff37a10f578f39b/index.js#L112) is where stream created but it never got `finish` event, because somehow it is created in a paused mode. And if reading isn't performed then `finish` event has never occures.

Probably you can solve this by adding `destStream.resume();` before calling `destStream.end();`

P.S.: I'm not totally sure if this is gulp-gh-pages bug or it is related with some underlying stream plugins.

**Comment by shinnn** [comment] 2015-10-19 17:38
Duplicate of https://github.com/shinnn/gulp-gh-pages/issues/74 and discussion goes there. Thanks for your investigation and detailed report though.

**Closed by shinnn** 2015-10-19 17:38 UTC
