### ISSUE TITLE
Failed on Windows

### ISSUE THREAD

**Issue by jdnichollsc** [shinnn/gulp-gh-pages#101] opened 2016-09-09 21:09 UTC
Hi man,

Yesterday this plugin works for me, but today show an error.
Check please http://screencast.com/t/bvcfltG3P

Regards, Nicholls

**Comment by shinnn** [comment] 2016-09-09 21:12
Duplicate of https://github.com/shinnn/gulp-gh-pages/issues/42

**Closed by shinnn** 2016-09-09 21:12 UTC
