### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [shinnn/gulp-gh-pages#124] opened 2018-07-20 12:44 UTC
whenever I try to `gulp deploy`, I get:

```
/(…)/node_modules/gift/lib/commit.js:145
      ref1 = /^.+? (.*) (\d+) .*$/.exec(line), m = ref1[0], actor = ref1[1], epoch = ref1[2];
                                                       ^

TypeError: Cannot read property '0' of null
    at Function.module.exports.Commit.actor (/(…)/node_modules/gift/lib/commit.js:145:56)
    at Function.module.exports.Commit.parse_commits (/(…)/node_modules/gift/lib/commit.js:111:21)
    at /(…)/node_modules/gift/lib/commit.js:55:39
    at ChildProcess.exithandler (child_process.js:264:7)
    at ChildProcess.emit (events.js:127:13)
    at maybeClose (internal/child_process.js:933:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

**Comment by shinnn** [comment] 2018-07-20 16:54
Duplicate of https://github.com/shinnn/gulp-gh-pages/issues/116

**Closed by shinnn** 2018-07-20 16:54 UTC
