### ISSUE TITLE
What is the order to make changes, push, and then use gulp deploy?

### ISSUE THREAD

**Issue by francisngo** [shinnn/gulp-gh-pages#106] opened 2017-01-02 19:19 UTC
I am having some issues that I cannot find the answer in the documentation.

I have had gulp-github-pages initially set up correctly but now when I want to make changes to the page, I don't know what the steps are. I tried to make change, do a gulp build, then git push, then gulp deploy but now my page doesn't exist. My gulp deploy is supposed to grab everything that is in the dist folder and deploys it to master. But now, github says my page is published on the default "name.github.io" instead of CNAME. 

Can someone help?

**Comment by shinnn** [comment] 2017-01-03 00:43
Duplicate of https://github.com/shinnn/gulp-gh-pages/issues/105.

**Closed by shinnn** 2017-01-03 00:43 UTC
