### ISSUE TITLE
Running gulpfile with this plugin after travis CI build

### ISSUE THREAD

**Issue by JonatanSalas** [shinnn/gulp-gh-pages#100] opened 2016-09-09 01:54 UTC
Hello! 

I want to ask you if this gulp plugin works or if you have checked that this works using Travis CI.
What I want to do, it's after every successful build on Travis deploy a demo to gh-pages.

**Comment by axe312ger** [comment] 2016-12-29 00:20
I am using the following at the moment, but actually i would love to have a plain node module without gulp for this neat idea.

```
const { join } = require('path')

const gulp = require('gulp')
const ghPages = require('gulp-gh-pages')

gulp.task('deploy', () => {
  console.log('Starting Github Pages deployment script...')
  return gulp.src(join(__dirname, '..', '..', 'dist', '**', '*'))
    .pipe(ghPages())
    .on('end', function () {
      console.log('Finished Github Pages deployment script...')
    })
})

gulp.start(['deploy'])
```

**Comment by axe312ger** [comment] 2016-12-29 00:22
Ohh and I just found this:
https://github.com/tschaub/gh-pages

**Comment by Snugug** [comment] 2017-01-11 19:02
@JonatanSalas This should do it for you https://github.com/shinnn/gulp-gh-pages/issues/80#issuecomment-271942002

**Comment by axe312ger** [comment] 2017-01-17 09:51
I guess it would be smarter to use an non-gulp version when gulp is not already in the workflow.

Non-gulp version: https://github.com/tschaub/gh-pages

**Comment by flyingliu** [comment] 2017-08-22 07:43
![](http://ww1.sinaimg.cn/large/006poVAQgy1fisjip0ma3j30a60833yh.jpg)

After using some pictures in my project, I found that I couldn't publish it successfully. Publish this folder does not copy pictures. After I delete part of the map, it can be released successfully. Why is that?

**Comment by shinnn** [comment] 2018-08-06 05:04
Duplicate of https://github.com/shinnn/gulp-gh-pages/issues/80.

**Closed by shinnn** 2018-08-06 05:04 UTC
Labels: question
